name: Hello world

on:
  push:
    branches: [ main ]

jobs:
  demo:
    uses: ./.github/workflows/env-template.yaml
    with:
      java_version: '17'
      working_dir: 'javatechbase'
      image_name: 'java-app'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}